// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/22/2024, 3:35:58 PM
const configMerger = require("/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/plugins/**/*.{js,ts,mjs}","/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/composables/**/*.{js,ts,mjs}","/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/utils/**/*.{js,ts,mjs}","/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/didowu/Desktop/CIS 115/Project/demmy.github.io/app.config.{js,ts,mjs}"] } }));

module.exports = config
